[features]
seeds = false
skip-lint = false
[programs.localnet]
quick_solang = "3hnqLxpAhYvtisxRqgumwpZu8ybYggMPAf38zRwPrr9A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "QUICKNODE_RPC_URL"
wallet = "/home/chuo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
